version: '3.8'

services:
  user-service:
    build: ./user_service
    ports:
      - "80:8080"
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - POSTGRES_URL=postgresql://postgres:password@postgres:5432/db
    depends_on:
      - rabbitmq
      - postgres
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
  course-service:
    build: ./course_service
    ports:
      - "80:8001"
    environment:
      USER_URL: http://user-service:80
    depends_on:
      - user-service