name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    name: Build and push to DockerHub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/course-service ./course_service

    - name: Log in to DockerHub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push tag to DockerHub
      run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/course-service:latest

    - name: Build docker image
      run: |
        docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/user-service:latest ./user_service

    - name: Login to YC REGISTRY
      uses: docker/login-action@v3.0.0
      with:
        registry: cr.yandex
        username: json_key
        password: ${{ secrets.YC_KEYS }}

    - name: Push to YC REGISTRY
      run: |
        docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/user-service:latest

