name: CI/CD pipline
on:
 push:
  branches: ["master"]
 pull_request:
  branches: ["master"]

jobs:
 build-and-push-to-dh:
  name: Build and push to DockerHub
  runs-on: ubuntu-latest
  needs: [ test ]
  steps:
   - uses: actions/checkout@v3

   - name: Build docker image
     run: |
      docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/course-service:latest

   - name: Log in to DockerHub
     uses: docker/login-action@v3.0.0
     with:
     username: ${{ secrets.DOCKER_USERNAME }}
     password: ${{ secrets.DOCKER_PASSWORD }}

   - name: Push tag to DockerHub
     run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/course-service:latest